### ISSUE TITLE
White and Black

### ISSUE THREAD

**Issue by lan3jur** [arpadHegedus/postcss-google-color#1]
Hi,
I love this plugin, but is it me or do
`google-color(white)` and `google-color(black)` not work?
In both cases, I get the output of
`color: #ccc`

Thanks.

**Comment by arpadHegedus** [comment]
That's true. When I developed the plugin Google hadn't included black and white in the palette. I've updated the list of colors since then, but forgot to include black and white. The reason it gives you #ccc, is because that is the fallback color in case the plugin cannot find the color you are looking for.

I will include black and white in the next update. Thanks for raising this.

**Comment by arpadHegedus** [comment]
With the new version, you should be able to use black and white as well.
